### ISSUE TITLE
SSLError in task collection

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-containers#106]
```
ERROR: Exception:
Traceback (most recent call last):
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 183, in __call__
    for chunk in chunks:
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 449, in _error_catcher
    raise SSLError(e)
pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: /data/app/Tasks/1/fractal-tasks-core/1.3.2/venv/bin/python -m pip install --upgrade pip
```

**Comment by jluethi** [comment]
Maybe it's a one-off on my side or something to do with an older version of docker running.

I've updated the docker version and tried again. Now it worked as expected. Not sure what caused it, but closing for now
